// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

#include <MCNPpluginPluginInfo.h>

VISIT_DATABASE_PLUGIN_ENTRY(MCNPplugin,Engine)

// ****************************************************************************
//  Method: MCNPpluginEnginePluginInfo::GetWriter
//
//  Purpose:
//      Sets up a MCNPplugin writer.
//
//  Returns:    A MCNPplugin writer.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************
avtDatabaseWriter *
MCNPpluginEnginePluginInfo::GetWriter(void)
{
    return NULL;
}

