// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

#include <MCNPPluginInfo.h>

VISIT_DATABASE_PLUGIN_ENTRY(MCNP,Engine)

// ****************************************************************************
//  Method: MCNPEnginePluginInfo::GetWriter
//
//  Purpose:
//      Sets up a MCNP writer.
//
//  Returns:    A MCNP writer.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************
avtDatabaseWriter *
MCNPEnginePluginInfo::GetWriter(void)
{
    return NULL;
}

